jobs:
  build-and-test:
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: java -jar target/backend-1.0.jar
