version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build and Test
          command: mvn test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
