version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Run Spring Boot Application
          command: java -jar target/backend-1.0.jar

workflows:
  sample:
    jobs:
      - build-and-test
