version: 2.1

jobs:
  build:
    docker:
      - image: openjdk:17-alpine
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

workflows:
  version: 2
  build:
    jobs:
      - build
